
import type { Metadata } from "next";
// import {  Vazirmatn } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local'

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });


// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });
//**S5-E2**//
// const vazirmatn=Vazirmatn({
//   subsets:['latin']
// })


const vazirmatn = localFont({
  variable:'--font-vazirmatn',
  src: [
    {
      path: './../fonts/vazirmatn/Vazirmatn-Thin.woff2',
      weight: '100',
      style: 'normal'
    },
    {
      path: './../fonts/vazirmatn/Vazirmatn-Medium.woff2',
      weight: '500',
      style: 'normal'
    }

  ]
})



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={vazirmatn.variable}>
      <head>
        <link href="https://vjs.zencdn.net/8.23.3/video-js.css" rel="stylesheet" />
      </head>
      {/* <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      > */}
      <body className="font-vazir">
        {children}
      </body>
    </html>
  );
}
